main:
  tmpPath: ../tmp/                                              # Path for temporary files
  logging:
    system: ../log/system.log                                   # Path to System-Log
    request: ../log/requests.log                                # Path to Request-Log
    error: ../log/error.log                                     # Path to Error-Log
  dateFormat: 'd.m.y H:i:s'                                     # Format for timestamps - See php.net/date for more information
  debugMode: false                                              # Enable debugging (debugging can also be enabled for a single run by setting the option --debug)
  user: www-data                                                # *NIX-User under which Pancake should run
  group: www-data                                               # *NIX-Group under which Pancake should run
  listenPorts:                                                  # List of ports to listen on (Recommended for HTTP: 80)
    - 200
  IPv4:                                                         # IPv4 network interfaces to listen on (use 0 to listen on all available interfaces)
    - 0
  IPv6:                                                         # IPv6 network interfaces to listen on (use ::0 to listen on all available interfaces)
    - ::0
  requestWorkers: 2                                             # Amount of RequestWorkers to run
  exposePancake: true                                           # If true, Pancake will send a "Server"-Header with Information about Pancake
  sizePrefix: bin                                               # "si" or "bin" - SI: 1000 Byte = 1 Kilobyte - Binary: 1024 Byte = 1 Kibibyte
  allowHEAD: true                                               # Whether to allow the "HEAD"-requestmethod
  allowTRACE: true                                              # Whether to allow the "TRACE"-requestmethod
  allowOPTIONS: true                                            # Whether to allow the "OPTIONS"-requestmethod
  requestWorkerLimit: 50000                                     # Limit of requests a RequestWorker may process until it has to be restarted (0 for no limit)
  maxConcurrent: 0                                              # Limit of concurrent connections a RequestWorker may hold open (0 for no limit)
  workerBootTime: 5                                             # The upper timelimit for a worker to boot (raise this when you're for example caching files that take long to load)
  writeBufferMin: 10240                                         # Minimum write buffer size that should be held in RAM
  writeBufferSoftMaxConcurrent: 50                              # Soft concurrent write buffer limit - When this limit is reached, Pancake won't allocate any buffers that are bigger than the minimum size anymore
  writeBufferHardMaxConcurrent: 2000                            # Hard concurrent write buffer limit - When this limit is reached, Pancake will try not to allocate any buffers anymore
  waitPHPWorkerBoot: true                                       # Wait for PHP-Workers to boot (should be disabled in shared environments)
  waitSlotTime: 5000                                            # When there is no PHPWorker available to serve a PHP-request, Pancake will check after waitslottime sec if a slot became available
  waitSlotWaitLimit: 5                                          # See above; this is the upper limit of wait-cycles until Pancake gives up on searching for a slot (for example: waitslottime = 5000; waitslotwaitlimit = 5 => Client will receive 500 Internal Server Error after 25 ms if no PHPWorker became available in those 25 ms)
  socketBacklog: 100                                            # Connection backlog for incoming requests
include:                                                        # Additional configuration-files to include
  - /usr/local/PancakeTest/Pancake/conf/vhosts
  - ../conf/mime.yml
moody:
  deletewhitespaces: false
  deletecomments: true
FastCGI:                                                        # FastCGI upstream server configurations
#  php:                                                         # This example configuration could be used to use the native php-fpm SAPI instead of the Pancake SAPI for executing PHP
#    type: unix
#    address: /var/run/php5-fpm.socket
#    mimeTypes:
#      - text/x-php
AJP13:                                                          # AJP13 upstream server configurations
#  jenkins:                                                     # This example configuration could be used to run Jenkins behind Pancake
#    type: ipv4
#    address: 127.0.0.1
#    port: 1030
#    maxconcurrent: 100